#!/usr/bin/env python3
# pragmma.py: Parrallel wrapper for Persistance for different trees generated by Disintegration

import ROOT
import subprocess
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor

# --- Config ---

runNr = 1010

# inputFile = Path.home() / "Lustre/gamma/ddas/RIBF249/rootfiles/ddas/disi/disi_1010.root"
inputFile = Path.home() / f"Lustre/gamma/ddas/RIBF249/rootfiles/ddas/disi/disi_{runNr}.root"
outputDir = Path.home() / "Lustre/gamma/ddas/RIBF249/rootfiles/ddas/pers"
settingsFile = Path.home() / "software/Salvador/settings/set_50Ca_C.dat"
max_workers = 20  # Number of parallel processes

# Ensure output directory exists
outputDir.mkdir(parents=True, exist_ok=True)

rootFile = ROOT.TFile(str(inputFile), "READ")
treeList = rootFile.GetListOfKeys()

# Filter non-empty trees 
trees_to_process = []
for tr in treeList:
    tree_name = tr.GetName()
    entries = rootFile.Get(tree_name).GetEntries()
    print(""f"Tree: {tree_name}, \t Entries: {entries}")
    if entries > 0:
        trees_to_process.append(tree_name)

print(f"Trees to process : {len(trees_to_process)}")

# run Persistence for each tree 
def run_persistence(tree_name):
    outputFile = outputDir / f"pers_{tree_name}_{runNr}.root"
    cmd = [
        "Persistence",
        "-i", str(inputFile),
        "-o", str(outputFile),
        "-s", str(settingsFile),
        "-tn", tree_name,
        "-wt", "0",
    ]
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)
    print(f"Finished: {tree_name}")


if __name__ == "__main__":

    # Run in parallel 
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        executor.map(run_persistence, trees_to_process)

