#!/usr/bin/env python3
# pragmma.py: Parrallel wrapper for Persistance for multiple root files and different trees generated by Disintegration

import ROOT
import subprocess
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor

# --- Config ---
# runNrs = [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013]   # 50Ca_C
# runNrs = [2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015 ,2016, 2017, 2018, 2019, 2020, 2021]    # 50Ca_Au
# runNrs = [3001, 3002, 3003, 3004, 3005]  # 50Ca_Be
# runNrs = [5002, 5003, 5004, 5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, 5013, 5014, 5015, 5016, 5017, 5018, 5019, 5020, 5021, 5022, 5023, 5024, 5025, 5026, 5027, 5028, 5029, 5030, 5031, 5032, 5033, 5034, 5035]  # 53Ca_Be
# runNrs = [
#     6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020,
#     6021, 6022, 6023, 6024, 6025, 6026, 6027, 6028, 6029, 6030, 6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038,
#     6039, 6040, 6041, 6042, 6043, 6044, 6045, 6046, 6047, 6048, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056,
#     6057, 6058, 6059, 6060, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6072, 6073, 6074,
#     6075, 6076, 6077, 6078, 6079, 6080, 6081, 6082, 6083, 6084, 6085, 6086, 6087, 6088, 6089, 6090, 6091, 6092,
#     6093, 6094, 6095, 6096, 6097, 6098, 6099, 6100, 6101, 6102, 6103, 6104, 6105, 6106, 6107, 6108
# ]
# runNrs = [
#     6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020,
# ]
runNrs = [2004,]

# --- Config ---

FILE_SUFFIX=""   
# FILE_SUFFIX="_new"   

inputFiles = [
    Path.home() / f"Lustre/gamma/ddas/RIBF249/rootfiles/ddas/disi/disi_{rn}{FILE_SUFFIX}.root"
    for rn in runNrs
]

for f in inputFiles:
    if not f.exists():
        raise FileNotFoundError(f"Missing input file: {f}")

SETTINGS_MAP = {
    1000: "set_49K_C.dat",
    2000: "set_49K_Au.dat",
    3000: "set_49K_Be.dat",
    5000: "set_51K_Be.dat",
    6000: "set_51K_Au.dat",
}

def choose_settings_file(runNrs):
    series = { (rn // 1000) * 1000 for rn in runNrs }

    if len(series) != 1:
        raise ValueError(f"Mixed run series detected: {sorted(series)}")

    series = series.pop()

    if series not in SETTINGS_MAP:
        raise ValueError(f"No settings file defined for {series} series")

    return Path.home() / "software/Salvador/settings" / SETTINGS_MAP[series]


outputDir = Path.home() / "Lustre/gamma/ddas/RIBF249/rootfiles/ddas/pers"
# settingsFile = Path.home() / "software/Salvador/settings/set_50Ca_C.dat"
max_workers = 20  # Number of parallel processes

settingsFile = choose_settings_file(runNrs)
print(f"Using settings file: {settingsFile}")


# Ensure output directory exists
outputDir.mkdir(parents=True, exist_ok=True)

# rootFile = ROOT.TFile(str(inputFile), "READ")
# treeList = rootFile.GetListOfKeys()

rootFile = ROOT.TFile(str(inputFiles[0]), "READ")
treeList = rootFile.GetListOfKeys()

# Filter non-empty trees 
trees_to_process = []
for tr in treeList:
    tree_name = tr.GetName()
    entries = rootFile.Get(tree_name).GetEntries()
    print(""f"Tree: {tree_name}, \t Entries: {entries}")
    if entries > 0:
        trees_to_process.append(tree_name)

print(f"Trees to process : {len(trees_to_process)}")


def run_persistence(tree_name):

    if len(runNrs) > 3:  # If many runs, use a generic tag for the series
        series = { (rn // 1000) * 1000 for rn in runNrs }
        if len(series) != 1:
            raise ValueError(f"Mixed run series detected: {series}")
        series_value = series.pop()          # extract the integer
        run_tag = f"all_{series_value}"     
    else:
        run_tag = "_".join(map(str, runNrs))

    outputFile = outputDir / f"pers_{tree_name}_{run_tag}.root"

    cmd = [
        "Persistence",
        "-i",
        *map(str, inputFiles),   
        "-o", str(outputFile),
        "-s", str(settingsFile),
        "-tn", tree_name,
        "-wt", "0",
    ]

    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)
    print(f"Finished: {tree_name}")



if __name__ == "__main__":

    # Run in parallel 
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        executor.map(run_persistence, trees_to_process)

